import type {Candidate,OccasionId,Template} from './types';
const F='/assets/fashion-grid.png' as const,B='/assets/beauty-grid.png' as const,P='/assets/places-grid.png' as const;
export const candidates:Candidate[]=[
{id:'berry-slip',occasion:'wedding',kind:'fashion',name:'Berry Hour',price:168,image:F,quad:'tl',attributes:{dressCode:'cocktail',weather:'warm',palette:'berry'},sourceLabel:'Atelier Edit',description:'Fluid satin, soft drape, dance-floor ready.'},{id:'sage-sculpt',occasion:'wedding',kind:'fashion',name:'Sage Structure',price:184,image:F,quad:'tr',attributes:{dressCode:'cocktail',weather:'mild',palette:'sage'},sourceLabel:'Form Studio',description:'Sculptural shoulder, polished and unexpected.'},
{id:'silver-mini',occasion:'birthday',kind:'fashion',name:'Silver Signal',price:142,image:F,quad:'bl',attributes:{dressCode:'nightlife',weather:'indoor',palette:'silver'},sourceLabel:'After Dark',description:'Sharp tailoring with full birthday energy.'},{id:'berry-bday',occasion:'birthday',kind:'fashion',name:'Afterglow Satin',price:168,image:F,quad:'tl',attributes:{dressCode:'dinner',weather:'indoor',palette:'berry'},sourceLabel:'Atelier Edit',description:'Romantic, fluid, and easy to style.'},
{id:'blue-utility',occasion:'festival',kind:'fashion',name:'Cobalt Utility',price:126,image:F,quad:'br',attributes:{dressCode:'festival',weather:'hot',palette:'cobalt'},sourceLabel:'Field Notes',description:'High-impact color with hands-free pockets.'},{id:'silver-fest',occasion:'festival',kind:'fashion',name:'Chrome Mini',price:142,image:F,quad:'bl',attributes:{dressCode:'festival',weather:'mild',palette:'silver'},sourceLabel:'After Dark',description:'Maximum shine, minimal layers.'},
{id:'rose-soft',occasion:'wedding',kind:'beauty',name:'Soft Rose Set',price:54,image:B,quad:'tl',attributes:{wearHours:10,complexity:'medium',waterproof:true},sourceLabel:'Sway Beauty',description:'Warm rose tones and a satin lip.'},{id:'berry-glow',occasion:'wedding',kind:'beauty',name:'Berry Glow',price:66,image:B,quad:'tr',attributes:{wearHours:12,complexity:'high',waterproof:true},sourceLabel:'Sway Beauty',description:'A graphic lip with luminous skin.'},
{id:'berry-statement',occasion:'birthday',kind:'beauty',name:'Main Character Lip',price:48,image:B,quad:'tr',attributes:{wearHours:12,complexity:'low',waterproof:true},sourceLabel:'Sway Beauty',description:'One bold move; everything else stays fresh.'},{id:'bronze-kit',occasion:'birthday',kind:'beauty',name:'Golden Hour Kit',price:62,image:B,quad:'br',attributes:{wearHours:8,complexity:'low',waterproof:false},sourceLabel:'Sway Beauty',description:'Soft bronze, forgiving, and fast.'},
{id:'chrome-eye',occasion:'festival',kind:'beauty',name:'Chrome Proof',price:58,image:B,quad:'bl',attributes:{wearHours:14,complexity:'high',waterproof:true},sourceLabel:'Sway Beauty',description:'Reflective eye with all-day setting power.'},{id:'bronze-fest',occasion:'festival',kind:'beauty',name:'Desert Bronze',price:62,image:B,quad:'br',attributes:{wearHours:8,complexity:'low',waterproof:false},sourceLabel:'Sway Beauty',description:'Low-maintenance warmth for long days.'},
{id:'garden-house',occasion:'wedding',kind:'hotel',name:'The Garden House',price:289,image:P,quad:'tl',attributes:{distance:'0.4 mi',walkable:true,amenities:'pool, breakfast'},sourceLabel:'Demo stays',description:'Intimate, walkable, and full of atmosphere.'},{id:'grand-hotel',occasion:'wedding',kind:'hotel',name:'The Grand Union',price:244,image:P,quad:'tr',attributes:{distance:'1.8 mi',walkable:false,amenities:'spa, late checkout'},sourceLabel:'Demo stays',description:'Full service with an easier group rate.'},
{id:'rooftop',occasion:'birthday',kind:'venue',name:'Orbit Rooftop',price:85,image:P,quad:'bl',attributes:{distance:'0.8 mi',groupSize:8,noise:'lively'},sourceLabel:'Demo venues',description:'Candlelight, skyline, and built-in celebration.'},{id:'garden-table',occasion:'birthday',kind:'venue',name:'Garden After Dark',price:72,image:P,quad:'tl',attributes:{distance:'2.1 mi',groupSize:10,noise:'intimate'},sourceLabel:'Demo venues',description:'A private-feeling dinner under the lights.'},
{id:'desert-camp',occasion:'festival',kind:'hotel',name:'Canvas Club',price:198,image:P,quad:'br',attributes:{distance:'0.6 mi',walkable:true,amenities:'shuttle, showers'},sourceLabel:'Demo stays',description:'Walkable glamping with real showers.'},{id:'city-base',occasion:'festival',kind:'hotel',name:'Palm City Base',price:164,image:P,quad:'tr',attributes:{distance:'7 mi',walkable:false,amenities:'pool, shuttle'},sourceLabel:'Demo stays',description:'More comfort, longer ride to the gates.'}
];
const mods=(o:OccasionId,place:'hotel'|'venue',placeLabel:string):Template['modules']=>[
{id:`${o}-fashion`,kind:'fashion',label:'Wear',question:'Which one feels more like you?',dimension:o==='festival'?'high-impact vs easy utility':'fluid vs structured',candidateIds:candidates.filter(x=>x.occasion===o&&x.kind==='fashion').map(x=>x.id)},
{id:`${o}-beauty`,kind:'beauty',label:'Glow',question:'What is the beauty move?',dimension:'statement vs low-maintenance',candidateIds:candidates.filter(x=>x.occasion===o&&x.kind==='beauty').map(x=>x.id)},
{id:`${o}-${place}`,kind:place,label:placeLabel,question:place==='venue'?'Where should the night happen?':'Where would you rather wake up?',dimension:place==='venue'?'energy vs intimacy':'atmosphere vs convenience',candidateIds:candidates.filter(x=>x.occasion===o&&x.kind===place).map(x=>x.id)}];
export const templates:Template[]=[
{id:'birthday',title:'Birthday Night Out',eyebrow:'The flagship edit',location:'Los Angeles, CA',date:'Saturday, September 12',budget:450,vibe:'polished, playful, camera-ready',accent:'#f06f4f',modules:mods('birthday','venue','Go'),prompt:'Organize my birthday options, check the plan, and show me the most useful next comparison.'},
{id:'wedding',title:'Wedding Weekend',eyebrow:'Cocktail dress code',location:'Santa Barbara, CA',date:'Saturday, October 3',budget:700,vibe:'romantic, modern, not too precious',accent:'#b16468',modules:mods('wedding','hotel','Stay'),prompt:'Help me organize my wedding weekend without choosing my style for me.'},
{id:'festival',title:'Festival Weekend',eyebrow:'Two days outside',location:'Indio, CA',date:'Friday, October 16',budget:520,vibe:'bold, durable, no basic festival clichés',accent:'#466fcb',modules:mods('festival','hotel','Stay'),prompt:'Check my festival options for heat, walking, and budget—then create a useful matchup.'}
];
export const getCandidate=(id:string)=>candidates.find(c=>c.id===id);
export const getTemplate=(id:OccasionId)=>templates.find(t=>t.id===id)!;
