import {candidates,getCandidate,getTemplate} from './catalog'; import type {Assessment,BoardState,ConstraintCheck,Insight,OccasionId,Vote} from './types';
export const newBoard=(occasionId:OccasionId='birthday'):BoardState=>{const t=getTemplate(occasionId);return{occasionId,brief:{location:t.location,date:t.date,budget:t.budget,vibe:t.vibe},activeModule:0,votes:[],friendVotes:[],reactions:{},contextRevealed:[],insights:[],assessments:[],winners:{},weights:{you:50,friends:30,fit:20},activity:[{id:crypto.randomUUID(),actor:'agent',text:'Demo board organized into three decisions. You still choose every winner.',time:Date.now()}],editBuilt:false,approved:false}};
export function vote(state:BoardState,moduleId:string,candidateId:string,role:'shopper'|'friend'='shopper'):BoardState{const target=role==='shopper'?'votes':'friendVotes';const v:Vote={id:crypto.randomUUID(),moduleId,candidateId,role,participantId:role==='shopper'?'you':'maya',changedAfterContext:state.contextRevealed.includes(moduleId)};return{...state,[target]:[...state[target].filter(x=>x.moduleId!==moduleId),v],winners:role==='shopper'?{...state.winners,[moduleId]:candidateId}:state.winners,activity:[...state.activity,{id:crypto.randomUUID(),actor:role==='shopper'?'you':'friend',text:`${role==='shopper'?'You':'Maya'} picked ${getCandidate(candidateId)?.name}.`,time:Date.now()}]}}
export function reveal(state:BoardState,moduleId:string):BoardState{return state.contextRevealed.includes(moduleId)?state:{...state,contextRevealed:[...state.contextRevealed,moduleId]}}
export function assessConstraints(state:BoardState,candidateId:string):Assessment{const c=getCandidate(candidateId);if(!c)throw new Error('Candidate not found');const checks:ConstraintCheck[]=[];const moduleCount=getTemplate(state.occasionId).modules.length;const categoryBudget=Math.round(state.brief.budget/moduleCount);checks.push({constraint:'Category budget',status:c.price<=categoryBudget?'meets':c.price<=categoryBudget*1.35?'tradeoff':'fails',evidence:`$${c.price} vs about $${categoryBudget} allocated`}); if(c.kind==='hotel'||c.kind==='venue')checks.push({constraint:'Distance',status:c.attributes.walkable===true||String(c.attributes.distance).startsWith('0.')?'meets':'tradeoff',evidence:`${c.attributes.distance} from the plan`});if(c.kind==='beauty')checks.push({constraint:'Routine effort',status:c.attributes.complexity==='low'?'meets':'tradeoff',evidence:`${c.attributes.complexity} complexity · ${c.attributes.wearHours}h wear`});if(c.kind==='fashion')checks.push({constraint:'Occasion fit',status:'meets',evidence:`Listed for ${c.attributes.dressCode} settings`});const score=Math.round(checks.reduce((n,x)=>n+(x.status==='meets'?100:x.status==='tradeoff'?65:x.status==='unknown'?50:20),0)/checks.length);return{candidateId,score,checks}}
export function addAssessment(state:BoardState,candidateId:string):BoardState{const a=assessConstraints(state,candidateId);return{...state,assessments:[...state.assessments.filter(x=>x.candidateId!==candidateId),a],activity:[...state.activity,{id:crypto.randomUUID(),actor:'agent',text:`Checked practical fit for ${getCandidate(candidateId)?.name}: ${a.score}/100. No aesthetic score added.`,time:Date.now(),undo:{type:'assessment',id:candidateId}}]}}
export function proposeInsight(state:BoardState,statement:string,scope:string,evidenceVoteIds:string[],confidence=.78):BoardState{const valid=state.votes.filter(v=>evidenceVoteIds.includes(v.id));if(valid.length<2)throw new Error('At least two shopper choices are required');const insight:Insight={id:crypto.randomUUID(),scope,statement,evidenceVoteIds,confidence,status:'pending'};return{...state,insights:[...state.insights,insight],activity:[...state.activity,{id:crypto.randomUUID(),actor:'agent',text:`Proposed a taste note from ${valid.length} of your choices. Review required.`,time:Date.now(),undo:{type:'insight',id:insight.id}}]}}
export function updateInsight(state:BoardState,id:string,status:Insight['status']):BoardState{return{...state,insights:state.insights.map(x=>x.id===id?{...x,status}:x),activity:[...state.activity,{id:crypto.randomUUID(),actor:'you',text:`Taste note ${status}.`,time:Date.now()}]}}
export function swayScore(state:BoardState,moduleId:string,candidateId:string){const own=state.votes.find(v=>v.moduleId===moduleId)?.candidateId===candidateId?100:25;const fs=state.friendVotes.filter(v=>v.moduleId===moduleId);const friend=fs.length?Math.round(fs.filter(v=>v.candidateId===candidateId).length/fs.length*100):null;const fit=state.assessments.find(a=>a.candidateId===candidateId)?.score??70;const denom=state.weights.you+(friend===null?0:state.weights.friends)+state.weights.fit;const total=Math.round((own*state.weights.you+(friend??0)*state.weights.friends+fit*state.weights.fit)/denom);return{total,you:own,friends:friend,fit}}
export function searchCatalog(query:string,occasion?:OccasionId){const q=query.toLowerCase();return candidates.filter(c=>(!occasion||c.occasion===occasion)&&(`${c.name} ${c.kind} ${c.description} ${Object.values(c.attributes).join(' ')}`.toLowerCase().includes(q)||!q)).slice(0,12)}
