import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Hotel,Search,Sparkles,ShoppingBag} from 'lucide-react';
import {getCandidate} from './catalog';
import {chooseShoppingCandidate,startShopping} from './decision-engine';
import type {BoardState,Candidate,ShoppingCategory,ShoppingIntent} from './types';

const positions={tl:'0% 0%',tr:'100% 0%',bl:'0% 100%',br:'100% 100%'};
const categoryCopy={
  outfit:{title:'An outfit',hint:'a wedding guest dress, jeans for going out, a festival set',budget:250,icon:ShoppingBag},
  beauty:{title:'A beauty item',hint:'a glossy lip, warm blush, waterproof eye look',budget:75,icon:Sparkles},
  hotel:{title:'A hotel',hint:'a walkable boutique stay, a group-friendly hotel',budget:350,icon:Hotel},
};

export function CategoryStart({shop}:{shop:(category:ShoppingCategory)=>void}){return <section className="category-start"><small>Start with one decision</small><h2>What are you looking for?</h2><p>No style quiz. Give us the must-haves, then teach Sway with your eyes.</p><div>{(Object.keys(categoryCopy) as ShoppingCategory[]).map(key=>{const c=categoryCopy[key],Icon=c.icon;return <button key={key} onClick={()=>shop(key)}><Icon/><span><b>{c.title}</b><small>{key==='outfit'?'Fashion':key==='beauty'?'Makeup + skincare':'Travel'}</small></span><ArrowRight/></button>})}</div></section>}

export default function Guided({category,state,setState,back}:{category:ShoppingCategory;state:BoardState;setState:(s:BoardState)=>void;back:()=>void}){
  const defaults=categoryCopy[category];
  const [intent,setIntent]=useState<ShoppingIntent>({category,query:'',budget:defaults.budget,size:'',color:'',location:'',mustHave:''});
  const [started,setStarted]=useState(Boolean(state.intent&&state.intent.category===category));
  const resolver=(id:string)=>state.customCandidates.find(c=>c.id===id)||getCandidate(id);
  const pair=state.comparisonQueue[state.comparisonIndex]?.map(resolver).filter(Boolean) as Candidate[]|undefined;
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!intent.query.trim())return;setState(startShopping(state,{...intent,query:intent.query.trim()}));setStarted(true)};
  if(!started)return <main className="intake"><button className="back" onClick={back}><ArrowLeft/> Back</button><div className="intake-card"><span className="step">01 · Set the guardrails</span><h1>Find {defaults.title.toLowerCase()}<br/><em>that feels like you.</em></h1><p>Structured details keep the results useful. The sentence is optional nuance—not a test of how well you can describe your style.</p><form onSubmit={submit}><label className="prompt"><Search/><span>What are you hunting for?</span><input autoFocus required value={intent.query} onChange={e=>setIntent({...intent,query:e.target.value})} placeholder={`Try “${defaults.hint.split(',')[0]}”`}/><small>Try: {defaults.hint}</small></label><div className="filter-grid"><label><span>Max price</span><div className="money">$<input type="number" min="10" max="5000" value={intent.budget} onChange={e=>setIntent({...intent,budget:+e.target.value})}/></div></label>{category==='outfit'&&<label><span>Size</span><select value={intent.size} onChange={e=>setIntent({...intent,size:e.target.value})}><option value="">Any size</option>{['XXS','XS','S','M','L','XL','XXL'].map(x=><option key={x}>{x}</option>)}</select></label>}{category==='hotel'&&<label><span>Location</span><input value={intent.location} onChange={e=>setIntent({...intent,location:e.target.value})} placeholder="City or neighborhood"/></label>}<label><span>{category==='hotel'?'Must have':'Color direction'}</span><input value={category==='hotel'?intent.mustHave:intent.color} onChange={e=>category==='hotel'?setIntent({...intent,mustHave:e.target.value}):setIntent({...intent,color:e.target.value})} placeholder={category==='hotel'?'Pool, walkable, 2 beds…':'Any, neutral, red…'}/></label></div><button className="cta" type="submit">Start choosing <ArrowRight/></button></form><aside><Sparkles/><p><b>Agent assist:</b> once this is set, ask your browser agent to find live products. It can add real links and prices directly to your matchups.</p></aside></div></main>;
  if(state.shortlist.length)return <Results state={state} items={state.shortlist.map(resolver).filter(Boolean) as Candidate[]} reset={()=>{setState({...state,intent:undefined,comparisonQueue:[],comparisonIndex:0,shortlist:[]});setStarted(false)}}/>;
  if(!pair||pair.length<2)return <main className="loading-state"><Sparkles/><h1>Your search is ready.</h1><p>Ask the browser agent to add live options, or continue with Sway’s starter set.</p><button className="cta" onClick={()=>setState(startShopping(state,intent))}>Use starter options</button></main>;
  return <main className="guided"><div className="guided-head"><button className="back" onClick={back}><ArrowLeft/> Exit</button><span>{state.comparisonIndex+1} of {state.comparisonQueue.length}</span><div className="bar"><i style={{width:`${(state.comparisonIndex/state.comparisonQueue.length)*100}%`}}/></div><small>{state.intent?.query}</small><h1>Which would you rather have?</h1><p>Go on instinct. Price and practical fit come back in your final three.</p></div><div className="guided-pair">{pair.map(item=><button key={item.id} onClick={()=>setState(chooseShoppingCandidate(state,item.id))}><div className="guided-art" role="img" aria-label={item.name} style={{backgroundImage:`url(${item.image})`,backgroundPosition:positions[item.quad],backgroundSize:item.live?'cover':'200% 200%'}}/><span>choose this</span><h2>{item.name}</h2><p>{item.description}</p></button>)}<i>or</i></div></main>
}

function Results({state,items,reset}:{state:BoardState;items:Candidate[];reset:()=>void}){const [approved,setApproved]=useState<string>();return <main className="results"><span className="step">Your shortlist · {state.intent?.query} · human ranked</span><h1>These three<br/><em>have your Sway.</em></h1><p>The order comes from your choices. Practical checks are shown separately—never blended into a hidden taste score.</p><div className="result-grid">{items.map((item,i)=><article className={approved===item.id?'approved-card':''} key={item.id}><b>0{i+1}</b><div className="guided-art" role="img" aria-label={item.name} style={{backgroundImage:`url(${item.image})`,backgroundPosition:positions[item.quad],backgroundSize:item.live?'cover':'200% 200%'}}/><small>{item.live?'Live result':item.sourceLabel}</small><h2>{item.name}</h2><p>{item.description}</p><div><strong>${item.price}</strong>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">View product</a>}</div><button onClick={()=>setApproved(item.id)}>{approved===item.id?<><Check/> Your final pick</>:<>Make this my pick <ArrowRight/></>}</button></article>)}</div><div className="result-actions"><button className="ghost" onClick={reset}>Start another search</button>{approved&&<div><Check/> Final choice approved by you. Sway did not purchase anything.</div>}</div></main>}
